# This rule is not used by the project service-control itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the app.teraskula.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: service-control
    app.kubernetes.io/managed-by: kustomize
  name: application-editor-role
rules:
- apiGroups:
  - app.teraskula.com
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.teraskula.com
  resources:
  - applications/status
  verbs:
  - get
