# This rule is not used by the project service-control itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to app.teraskula.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: service-control
    app.kubernetes.io/managed-by: kustomize
  name: application-viewer-role
rules:
- apiGroups:
  - app.teraskula.com
  resources:
  - applications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.teraskula.com
  resources:
  - applications/status
  verbs:
  - get
