apiVersion: app.teraskula.com/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: service-control
    app.kubernetes.io/managed-by: kustomize
  name: testapp1
  namespace: testnamespace
spec:
  image: nginx:latest
  replicas: 1
