{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "service-control.fullname" . }}-manager-rolebinding
  labels:
    {{- include "service-control.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ include "service-control.releaseName" . }}
    meta.helm.sh/release-namespace: {{ include "service-control.releaseNamespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "service-control.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "service-control.serviceAccountName" . }}
  namespace: {{ include "service-control.releaseNamespace" . }}
{{- end }}