apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service-control.fullname" . }}
  labels:
    {{- include "service-control.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ include "service-control.releaseName" . }}
    meta.helm.sh/release-namespace: {{ include "service-control.releaseNamespace" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "service-control.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "service-control.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "service-control.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: manager
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /manager
          args:
            - --health-probe-bind-address=:{{ .Values.controller.health.port }}
            {{- if .Values.controller.metrics.enabled }}
            - --metrics-bind-address=:{{ .Values.controller.metrics.port }}
            - --metrics-secure={{ .Values.controller.metrics.secure }}
            {{- else }}
            - --metrics-bind-address=0
            {{- end }}
            {{- if .Values.controller.leaderElection.enabled }}
            - --leader-elect=true
            {{- else }}
            - --leader-elect=false
            {{- end }}
            {{- if .Values.controller.webhook.enabled }}
            - --webhook-cert-path={{ .Values.controller.webhook.certPath }}
            {{- end }}
          ports:
            - name: health
              containerPort: {{ .Values.controller.health.port }}
              protocol: TCP
            {{- if .Values.controller.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.controller.metrics.port }}
              protocol: TCP
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}