apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-control.fullname" . }}
  labels:
    {{- include "service-control.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.controller.health.port }}
      targetPort: health
      protocol: TCP
      name: health
    {{- if .Values.controller.metrics.enabled }}
    - port: {{ .Values.controller.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "service-control.selectorLabels" . | nindent 4 }}