{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "service-control.serviceAccountName" . }}
  labels:
    {{- include "service-control.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ include "service-control.releaseName" . }}
    meta.helm.sh/release-namespace: {{ include "service-control.releaseNamespace" . }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}